### ISSUE TITLE
[DELETE] 중복 메소드 삭제

### ISSUE THREAD

**Issue by thguss** [Team-Sopetit/Sopetit-server#106]
[comment]: <> (priority 와 task size를 뱃지로 정해주세요)

**📌 상세 설명**

[comment]: <> (이슈에 대한 설명을 적어주세요)
member.initHappinessRoutine
member.deleteHappinessRoutine
위 두 메소드가 중복되어 하나 삭제해야 합니다.

**📝 체크리스트**

[comment]: <> (해야 할 일들을 상세히 나눠 적어주시면 좋아요)

- [x] resetHappinessRoutine() 으로 통일

**Comment by Chan531** [comment]
빠른 이슈 좋아요~

**Comment by csb9427** [comment]
저거 누가 고쳐야 하는 거? 아무나 가져가서 고치는 건가유??

**Comment by csb9427** [comment]
member.resetHappinessRoutine
