### ISSUE TITLE
[CHORE] meesage 범인 나와라.

### ISSUE THREAD

**Issue by Chan531** [Team-Sopetit/Sopetit-server#111]
**📌 상세 설명**

![image](https://github.com/Team-Sopetit/Sopetit-server/assets/81404890/cfc7f4a9-d18b-4a0a-b215-83888deae693)

**📝 체크리스트**

- [x] 나 아님 ㅋㅋㅋㅋㅋㅋ

**Comment by thguss** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 나일수도
