### ISSUE TITLE
[TEST] 단위 테스트 코드 (Service)

### ISSUE THREAD

**Issue by thguss** [Team-Sopetit/Sopetit-server#146]
[comment]: <> (priority 와 task size를 뱃지로 정해주세요)

**📌 상세 설명**

[comment]: <> (이슈에 대한 설명을 적어주세요)
단위 테스트 코드를 작성합니다.

<br/>

- [x] 데일리 루틴 테마 전체 조회
- [x] 테마별 데일리 루틴 목록 조회
- [x] 테마 리스트별 데일리 루틴 목록 조회
- [x] 회원 데일리 루틴 추가 ✔
- 회원 데일리 루틴 삭제 -> 통합 테스트로 가져갈 예정
- [x] 회원 데일리 루틴 달성 ✔
- [x] 회원 데일리 루틴 목록 조회 ✔
- [x] (후순위) 인형 이미지 조회 (찬이 해줌)
- (후순위) 회원 행복 루틴 목록 조회 -> 후순위, 테스트코드 컨벤션 정리 후 별도 진행

**Comment by csb9427** [comment]
과연 언제 다 작성이 가능해질까
