### ISSUE TITLE
[FIX] 행복 솜뭉치 먹인 개수 기록해두기

### ISSUE THREAD

**Issue by Chan531** [Team-Sopetit/Sopetit-server#167]
**📌 상세 설명**

행복 솜뭉치 먹인 개수 기록해두기

**📝 체크리스트**

- [ ] 행복 솜뭉치 먹인 개수 기록해두기

**Comment by thguss** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
