### ISSUE TITLE
서버 멘토링 qna

### ISSUE THREAD

**Issue by daehwan2da** [Team-Sopetit/Sopetit-server#170]
https://github.com/daehwan2da/server-qna/issues/4#issue-2090770843

**Comment by thguss** [comment]
한 번씩 읽어보고 아래 각자 이름에 체크 부탁드려요 :)
- [ ] 승빈
- [ ] 찬
- [ ] 소현

마지막 체크 표시하는 사람이 이슈 닫기 ㅎㅁㅎ
