### ISSUE TITLE
[CHORE] Constant, ValueConfig 병합 제안

### ISSUE THREAD

**Issue by thguss** [Team-Sopetit/Sopetit-server#173]
[comment]: <> (priority 와 task size를 뱃지로 정해주세요)

**📌 상세 설명**

[comment]: <> (이슈에 대한 설명을 적어주세요)
- 둘 다 특정 값을 저장하는 같은 역할을 하기 때문에 병합해도 된다고 생각하여 해당 내용을 제안합니다.
- static 사용 또한 리소스 낭비로 이어지지 않을까 걱정되네요ㅠㅠ!!

**📝 체크리스트**

[comment]: <> (해야 할 일들을 상세히 나눠 적어주시면 좋아요)

- [ ] 스크럼 중 논의 예정

**Comment by csb9427** [comment]
오호 이런 논의 즐거워요 이따 스크럼때 한 번 더 언급 부탁드립니당
