### ISSUE TITLE
[ADD] 도전 루틴 삭제 및 추가

### ISSUE THREAD

**Issue by Chan531** [Team-Sopetit/Sopetit-server#283]
**📌 상세 설명**
- 도전 루틴 삭제 및 추가 api v2 개발용 이슈입니다.

**📝 체크리스트**

- [ ] 도전 루틴 삭제 api v2
- [ ] 도전 루틴 추가 api v2

**Comment by thguss** [comment]
리팩토링 과정 중 반영되었으므로 이슈를 close합니다.
