### ISSUE TITLE
[REFACTOR] AuthServiceImpl에 adapter 적용

### ISSUE THREAD

**Issue by Chan531** [Team-Sopetit/Sopetit-server#285]
**📌 상세 설명**
- AuthServiceImpl에 아직 adapter를 사용하지 않는 코드가 있어 이를 수정하고자 합니다.

**📝 체크리스트**

- [ ] AuthServiceImpl에 adapter 적용

**Comment by thguss** [comment]
리팩토링 과정 중 반영되었으므로 이슈를 close 합니다.
