### ISSUE TITLE
[FIX] Swagger Header 인증 오류

### ISSUE THREAD

**Issue by Chan531** [Team-Sopetit/Sopetit-server#333]
[comment]: <> (priority 와 task size를 뱃지로 정해주세요)

**📌 상세 설명**

- 메소드 파라미터에 RequestHeader가 명시된 api가 스웨거에서 원활히 동작하지 않음. (postman에서는 정상 동작)

**📝 체크리스트**

[comment]: <> (해야 할 일들을 상세히 나눠 적어주시면 좋아요)

- [ ] 버그 수정

**Comment by thguss** [comment]
해결
