### ISSUE TITLE
[RENAME] ResponseMessage를 SuccessMessage로 바꾸는 것에 대한 논의

### ISSUE THREAD

**Issue by Chan531** [Team-Sopetit/Sopetit-server#47]
[comment]: <> (priority 와 task size를 뱃지로 정해주세요)

**📌 상세 설명**

ResponseMessage를 SuccessMessage로 바꾸는 것에 대한 논의

**📝 체크리스트**

[comment]: <> 
- [x] SuccessMessage로 통일

**Comment by thguss** [comment]
SuccessMessage로 논의 완료
