### ISSUE TITLE
[REFACTOR] null을 허용하지 않는 원시값을 쓰는 것에 대한 논의

### ISSUE THREAD

**Issue by Chan531** [Team-Sopetit/Sopetit-server#61]
[comment]: <> (priority 와 task size를 뱃지로 정해주세요)

**📌 상세 설명**

```
@Override
public MemberDailyRoutinesResponse getMemberDailyRoutines(long memberId) {
	val member = findMember(memberId);
	val routines = memberDailyRoutineRepository.findAllByMember(member);
	return MemberDailyRoutinesResponse.of(routines);
}
```

null 값이 들어오는 것을 허락하지 않고자 첫번째 메서드는 long memberId를 쓰는 모습을 확인할 수 있다.

```
private Member findMember(Long id) {
	return memberRepository.findById(id);
}
```

반면 우리가 보편적으로 사용하는 findMember 메서드에서는 Long id를 사용하는 모습을 확인할 수 있다.
하나로 통일하는 것이 좋을 거 같아서 이슈를 생성했다.

**📝 체크리스트**

[comment]: <> (해야 할 일들을 상세히 나눠 적어주시면 좋아요)

- [ ] 어떻게 할까요?

**Comment by csb9427** [comment]
저는 고민해 봤는데 long 원시 값 사용하는 것이 좋을 거 같습니다. 
실제로 null을 따로 처리하더라도 long을 사용해 null을 받지 않겠다는 것을 표현한다면 코드가 전달하는 메시지로도 충분히 좋다고 생각합니다!

**Comment by thguss** [comment]
long 타입으로 논의 완료
