### ISSUE TITLE
[FIX] 행복루틴 추가 병합 충돌 대응

### ISSUE THREAD

**Issue by thguss** [Team-Sopetit/Sopetit-server#81]
[comment]: <> (priority 와 task size를 뱃지로 정해주세요)

**📌 상세 설명**

[comment]: <> (이슈에 대한 설명을 적어주세요)
안녕하세요. 회원 별 행복 루틴 조회를 위해서 행복 루틴 추가 API와 병합해야 합니다.
병합 중 이미 존재하는 에러가 발생하여 API를 개발하기 위해 먼저 해결했습니다ㅠㅠ

**📝 체크리스트**

[comment]: <> (해야 할 일들을 상세히 나눠 적어주시면 좋아요)

- [ ]

- [ ]

**Comment by csb9427** [comment]
감사합니다 ㅜㅜㅜ 덕분에 제가 쉴 수 있어요
